sample_questions = [
    "What is the capital of France?", "What is 2+2?", "What color is the sky?", "What is H2O?",
    "Which planet is red?", "What is the opposite of hot?", "What is the square root of 9?",
    "What gas do we breathe?", "What is the freezing point of water?", "What is the largest ocean?",
    "What is the currency of Japan?", "Who painted the Mona Lisa?", "What is the speed of light?",
    "What language is spoken in Brazil?", "What is 5*5?", "What planet do we live on?",
    "What is the capital of India?", "What is 10 divided by 2?", "What is the chemical symbol for gold?",
    "Who wrote '1984'?", "What is the smallest prime number?", "What is the capital of Italy?",
    "How many continents are there?", "What shape has three sides?", "What is the capital of Germany?",
    "What is the national sport of Canada?", "What is water made of?", "How many days in a week?",
    "What is the opposite of big?", "What is the plural of mouse?", "Which animal barks?",
    "How many hours in a day?", "What do bees produce?", "What is the capital of Egypt?",
    "What organ pumps blood?", "What is the color of bananas?", "What is the tallest mountain?",
    "What is the hottest planet?", "What is 12 x 12?", "What does DNA stand for?",
    "What is the capital of Spain?", "What planet is closest to the sun?", "What is the boiling point of water?",
    "Who is the Greek god of war?", "Which ocean is the largest?", "What is 3 cubed?",
    "What’s the capital of Canada?", "What is 100 in Roman numerals?", "What is the square root of 64?",
    "What is a baby dog called?", "What is a synonym for quick?", "What is the opposite of old?",
    "What’s the capital of Russia?", "How many legs does a spider have?", "What is the color of emerald?",
    "What shape has four equal sides?", "What is a group of lions called?", "What is the national animal of USA?",
    "How many seconds in a minute?", "Which planet has rings?", "What is 0 divided by 1?",
    "What’s the capital of Australia?", "What is the largest mammal?", "What is the color of coal?",
    "What is 1+1?", "How many letters in the alphabet?", "What is the moon made of?",
    "What is the longest river?", "What color is a ruby?", "What sound does a cat make?",
    "What gas do plants produce?", "What is 11 squared?", "What is a triangle?",
    "What is the currency of the USA?", "What is heavier: iron or cotton?", "What is the opposite of fast?",
    "How many colors in a rainbow?", "What does a thermometer measure?", "What is 20% of 100?",
    "Which planet is blue?", "What is the main ingredient in bread?", "How many bones in the human body?",
    "What is a group of wolves called?", "What is a young sheep called?", "What is Earth's natural satellite?",
    "What is the name for a three-legged stand?", "What is 50 + 50?", "Which bird can mimic humans?",
    "What’s the capital of China?", "What do cows drink?", "What organ helps us breathe?",
    "What is an antonym of happy?", "What is the hardest natural substance?", "Which metal is liquid at room temp?",
    "What is the capital of South Korea?", "What is 7 factorial?", "What is the chemical symbol for iron?",
    "How many degrees in a right angle?", "What is the opposite of clean?", "What’s the capital of Mexico?",
    "What is the smallest bone in the body?", "What part of the body helps you see?", "What is 2 to the power of 5?",
    "How many planets in the solar system?", "What is the main gas in Earth’s atmosphere?", "Which bird lays the largest eggs?",
    "What planet is known for its rings?", "What is the lightest element?", "What is the largest desert?",
    "What is 9 squared?", "Which planet is known as the evening star?", "What is the study of life called?",
    "Which gas is used in balloons?", "What is the capital of the UK?", "What is the opposite of up?",
    "What color are strawberries?", "What does a botanist study?", "What is a baby cat called?",
    "How many minutes in an hour?", "What is the fastest bird?", "How many meters in a kilometer?",
    "What is the main language in France?", "How many hearts does an octopus have?", "What is a polygon with 6 sides?",
    "What is 1000 divided by 10?", "What vitamin do we get from sunlight?", "What part of the body has the femur?",
    "What is the capital of Argentina?", "What is 14 + 7?", "What fruit is yellow and curved?",
    "What is the capital of Pakistan?", "What’s the 26th letter of the alphabet?", "What is 90 divided by 3?",
    "What does HTML stand for?", "What is a synonym for large?", "How many fingers do humans have?",
    "What is the boiling point of water in Fahrenheit?", "Which planet has the most moons?",
    "What is the speed of sound?", "What is the capital of Turkey?", "What’s the chemical formula of salt?",
    "How many zeros in a million?", "What is the largest land animal?", "What is the national flower of Japan?",
    "What is the capital of Nigeria?", "What is the main source of energy for Earth?", "What’s the opposite of empty?",
    "What is the capital of Kenya?", "What’s the longest bone in the body?", "What part of the plant makes food?",
    "What’s the capital of Thailand?", "What is the coldest place on Earth?", "What is 1 kilometer in meters?",
    "What is 8 times 7?", "What are the colors of the flag of India?", "What is the function of the heart?",
    "What is the human body mostly made of?", "Which animal is known as the ship of the desert?",
    "What is the capital of Sweden?", "How many teeth does an adult human have?", "What is 15 squared?",
    "What is the meaning of CPU?", "What is the capital of Norway?", "What is the name for molten rock?",
    "How many continents touch the Pacific?", "What’s the full form of RAM?", "What’s the capital of Iraq?",
    "What organ is vital for detoxification?", "Which metal is in thermometers?", "What color are carrots?",
    "What type of energy is sunlight?", "What shape is a pizza slice?", "What is the capital of Greece?",
    "What is the color of blood?", "How many toes does a person have?", "What planet is known for storms?",
    "What is the main ingredient in sushi?", "What is 6x6?", "What is the opposite of full?",
    "Which bird is the symbol of peace?", "What’s the capital of Vietnam?", "What is Earth's core made of?",
    "How many centimeters in a meter?", "What is a synonym for cold?", "What does NASA stand for?",
    "What is the capital of Bangladesh?", "How many legs does an insect have?", "Which animal is the tallest?",
    "What is the hardest rock?", "What fruit has seeds on the outside?", "What is the capital of Nepal?",
    "What country is known for tulips?", "What shape is a stop sign?", "What is a baby frog called?",
    "What is the capital of Iran?", "Which bird cannot fly?", "Which country has the largest population?",
    "What is the hottest continent?", "What insect produces honey?", "What is a group of fish called?",
    "What animal has a trunk?", "What do you call molten rock after it erupts?", "What is 16 divided by 4?",
    "What is the capital of Malaysia?", "Which planet spins the fastest?", "What does CPU stand for?",
    "What is a synonym of intelligent?", "Which blood type is universal donor?", "What is the capital of Portugal?",
    "What is a male cow called?", "What is the coldest planet?", "Which gas do humans exhale?",
    "How many months in a year?", "What is the tallest building in the world?", "What organ filters blood?",
    "What is the largest internal organ?", "What is the capital of Switzerland?", "What is the longest word in English?",
    "Which part of the eye gives color?", "How many chambers does the heart have?", "What is the capital of Poland?",
    "What is the most spoken language?", "Which gas is needed for fire?", "What is the name of Earth's galaxy?",
    "What is the fastest land animal?", "How many ribs does a human have?", "What is the capital of Brazil?",
    "What is the national bird of India?", "What is the currency of UK?", "What is the symbol for potassium?",
    "What’s the study of stars?", "What is the capital of Saudi Arabia?", "What is the heaviest element?",
    "What is the capital of Sri Lanka?", "Which bird is nocturnal?", "What does USB stand for?",
    "What is the largest country?", "How many hours in a week?", "What do you call animals that eat plants?",
    "What does HTTP stand for?", "Which gas is used in fire extinguishers?", "Which metal is most abundant on Earth?",
    "What does Wi-Fi stand for?", "What is the rarest blood type?", "Which animal can change color?",
    "How many sides in a decagon?", "What is the closest star to Earth?", "What is the national sport of India?",
    "What’s the capital of New Zealand?", "What is the first element in the periodic table?",
    "What is the largest island?", "Which insect has beautiful wings?", "What is the capital of Finland?"
]

def get_array():
    """
    Returns a question from the sample_questions list based on the provided index.
    
    :param index: The index of the question to retrieve.
    :return: The question string if index is valid, otherwise None.
    """
    return sample_questions